name: env_ML2
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py313h2cb717b_0
  - brotli-python=1.0.9=py313h5da7b33_9
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.4.26=h4c7d964_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.1=py313h214f63a_0
  - cpython=3.13.3=py313hd8ed1ab_101
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.8.14=py313h5813708_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dill=0.4.0=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.2.0=pyhd8ed1ab_0
  - fonttools=4.55.3=py313h827c3e9_0
  - freetype=2.13.3=h57928b3_1
  - glib=2.84.1=h3d4babf_0
  - glib-tools=2.84.1=h4394cf3_0
  - gst-plugins-base=1.24.11=h3fe0a9e_0
  - gstreamer=1.24.11=h233a61a_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=75.1=he0c23c2_0
  - imbalanced-learn=0.13.0=pyhd8ed1ab_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=9.1.0=pyhca29cf9_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.0=pyhd8ed1ab_0
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh5737063_1
  - kiwisolver=1.4.8=py313h5da7b33_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h5da7b33_0
  - libclang13=20.1.3=default_h6e92b77_0
  - libdeflate=1.23=h76ddb4d_0
  - libexpat=2.7.0=he0c23c2_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.13.3=h57928b3_1
  - libfreetype6=2.13.3=h0b5ce68_1
  - libgcc=14.2.0=h1383e82_2
  - libglib=2.84.1=h7025463_0
  - libgomp=14.2.0=h1383e82_2
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.0.3=h827c3e9_0
  - liblzma=5.8.1=h2466b09_0
  - libmpdec=4.0.0=h2466b09_0
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.47=had7236b_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.49.1=h67fdade_2
  - libtiff=4.7.0=h797046b_3
  - libvorbis=1.3.7=he774522_0
  - libwebp-base=1.5.0=h3b0e114_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libzlib=1.3.1=h2466b09_2
  - lightgbm=4.6.0=py313h5da7b33_0
  - llvmlite=0.44.0=py313hb80970b_1
  - loguru=0.7.2=py313hfa70ccb_2
  - matplotlib=3.10.0=py313haa95532_1
  - matplotlib-base=3.10.0=py313h7aa5d4e_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - missingno=0.5.2=pyhd8ed1ab_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py313h827c3e9_2
  - mkl_fft=1.3.11=py313h827c3e9_0
  - mkl_random=1.2.8=py313hce38976_0
  - narwhals=1.38.0=pyhe01879c_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numba=0.61.2=py313h4ca4f0f_0
  - numexpr=2.10.1=py313h4cd664f_0
  - numpy=2.2.4=py313he6dc315_0
  - numpy-base=2.2.4=py313h6011491_0
  - openjpeg=2.5.3=h4d64b90_0
  - openssl=3.5.0=ha4e3fda_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py313h5da7b33_0
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=h3d7b363_2
  - pendulum=3.1.0=py313hf3b5b86_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py313hda88b71_0
  - pip=25.0.1=pyh145f28c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.7=pyh29332c3_0
  - plotly=6.0.1=pyhd8ed1ab_0
  - ply=3.11=py313haa95532_1
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py313ha7868ed_0
  - pthread-stubs=0.3=h3c9f919_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.0=py313haa95532_0
  - pyqt=5.15.10=py313h5da7b33_1
  - pyqt5-sip=12.13.0=py313h827c3e9_1
  - python=3.13.3=h261c0b1_101_cp313
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.13=7_cp313
  - pytz=2024.1=py313haa95532_0
  - pywin32=307=py313h5813708_3
  - pyzmq=26.4.0=py313h2100fd5_0
  - qt-main=5.15.15=h9151539_3
  - referencing=0.36.2=pyh29332c3_0
  - rpds-py=0.24.0=py313h54fc02f_0
  - scikit-learn=1.6.1=py313h4f67946_0
  - scipy=1.15.2=py313hd4070db_1
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=72.1.0=py313haa95532_0
  - shap=0.46.0=py313hce38976_0
  - sip=6.7.12=py313h5da7b33_1
  - six=1.17.0=pyhd8ed1ab_0
  - sklearn-compat=0.1.3=pyhd8ed1ab_0
  - slicer=0.0.8=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.4=py313h8e081ca_0
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - time-machine=2.16.0=py313ha7868ed_0
  - tk=8.6.13=h5226925_1
  - tornado=6.4.2=py313ha7868ed_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.22621.0=h57928b3_1
  - vc=14.3=h2b53caa_26
  - vc14_runtime=14.42.34438=hfd919c2_26
  - vs2015_runtime=14.42.34438=h7142326_26
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - win32_setctime=1.2.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - zeromq=4.3.5=ha9f60a1_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - certifi==2025.4.26
      - ucimlrepo==0.0.7
      - yellowbrick==1.5
prefix: C:\Users\HP\anaconda3\envs\env_ML2
